# Generated by Django 3.2.8 on 2021-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCrudApp', '0003_auto_20211102_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
